server {
  root /var/www/;

  location / {
    try_files $uri $uri/ = /index.html;
  }
  location /birthday {
    try_files $uri $uri/ = /index.html;
  }
  location /api {
    proxy_pass http://server:8000;
    add_header 'Access-Control-Allow-Origin' '*' always;
  }
}
