when:
  event: push
  branch: ${CI_REPO_DEFAULT_BRANCH}
steps:
  projectbuild:
    image: frederikbrothimg/rustleptos:latest
    commands:
      - echo ${CI_COMMIT_TAG}
      - sccache -s
      - export RUSTC_WRAPPER=sccache
      - wget -qO- https://github.com/trunk-rs/trunk/releases/download/v0.21.14/trunk-aarch64-unknown-linux-gnu.tar.gz | tar -xzf-
      - ./trunk build --release --config .
      - zip -r dist.zip dist/*
      - mv dist nginx/dist
  docker-build:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: frederikbrothimg/cv-site-nginx
      context: nginx/.
      dockerfile: nginx/Dockerfile
      platforms: linux/arm64/v8
      tag: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
  send-webhook:
    image: debian
    commands:
      - curl webhook.frederikbroth.dk/deploysite?secret=$${WEBHOOK_SECRET}
    environment:
      WEBHOOK_SECRET:
        from_secret: webhook_secret
