when:
  event: push
  branch: ${CI_REPO_DEFAULT_BRANCH}

steps:
  release-helper:
    image: woodpeckerci/plugin-ready-release-go:next
    pull: true
    settings:
      release_branch: ${CI_REPO_DEFAULT_BRANCH}
      git_email: frederikbroth@gmail.com
      forge_token:
        from_secret: GITHUB_SECRET


