when:
  event: [tag]
  branch: ${CI_REPO_DEFAULT_BRANCH}


steps:
  a-test-step:
    image: debian
    commands:
      - echo "suck my fucking dick" > test.txt
  publish:
    image: woodpeckerci/plugin-release
    settings:
      files:
        - 'test.txt'
        # Could also be "hello-world*" to match both
      api_key:
        from_secret: GITHUB_SECRET
