when:
  event: [tag, push]
  branch: ${CI_REPO_DEFAULT_BRANCH}

steps:
  a-test-step:
    image: debian
    commands:
      - touch test.txt
  publish:
    image: woodpeckerci/plugin-release
    settings:
      files:
        - 'touch.txt'
        # Could also be "hello-world*" to match both
      api_key:
        from_secret: GITHUB_SECRET
