when:
  event: [tag]
  branch: ${CI_REPO_DEFAULT_BRANCH}
steps:
  a-test-step:
    image: rust
    commands:
      - rustup target add wasm32-unknown-unknown
  
  publish:
    image: woodpeckerci/plugin-release
    settings:
      files:
        # Could also be "hello-world*" to match both
      api_key:
        from_secret: GITHUB_SECRET
