when:
  event: [tag]
  branch: ${CI_REPO_DEFAULT_BRANCH}
steps:
  a-test-step:
    image: rust
    commands:
      - rustup target add wasm32-unknown-unknown
      - wget -qO- https://github.com/trunk-rs/trunk/releases/download/v0.20.2/trunk-aarch64-unknown-linux-gnu.tar.gz.sha256 | tar -xzf-
      - ./trunk build --release
      - zip dist.zip dist/*
  publish:
    image: woodpeckerci/plugin-release
    settings:
      files:
        # Could also be "hello-world*" to match both
      api_key:
        from_secret: GITHUB_SECRET
